Repository ArduPilot/pymavlink, pull requests merged in 2024-09, with the labels that each got.

#957 Add mavftp library and example code that uses it
  examples/mavftp_example.py
  mavftp.py
  tests/test_mavftp.py
Labels: enhancement, DevCallEU

#975 mavutil: WebSockets: fix wsproto import for newer python versions
  mavutil.py
Labels: DevCallTopic

#977 mavwp: mark re.match pattern as regex string
  mavwp.py
Labels: NeedsTesting
